server:
  port: 1996
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://95.179.159.62:3308/shop

mybatis:
  mapper-locations: classpath:mapper/**/*.xml